name = "backend"
compatibility_date = "2024-07-21"

[vars]
DATABASE_URL= "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTA5Y2FjMTMtYzZjOS00YmRjLTgwNmYtMGJhNDkxZjJiNGMwIiwidGVuYW50X2lkIjoiOTJlNDExMDc2Njg3ODQ4ZmUxYzdjNGMxYjVlODA4MmUxZGEzOWU4OGNjYzhhZTg2YmZhMzZlOTdhYTQwNDAzZSIsImludGVybmFsX3NlY3JldCI6IjZjNjc4ZmFhLTY2OTktNDQxNS05MjdlLThmNTFiNzVhNjgxNCJ9.A4o8caGpBTNKb9HAiMkdk1Uh8KVKW2MoVpejUEXdE_8"
JWT_SECRET = "abcdefghijklmnop"
